### ISSUE TITLE
Timeout Error When Sending Handshake to `tcp://openapi-quote.longportapp.com:2020`

### ISSUE THREAD

**Issue by iiiyu** [longportapp/openapi-protocol#14]
Hi,

I followed the instructions from [this documentation](https://open.longportapp.com/en/docs/socket/protocol/handshake) to send a handshake packet to `tcp://openapi-quote.longportapp.com:2020`, but I encountered a timeout error. However, I was able to successfully send a handshake packet to `tcp://openapi-trade.longportapp.com:2020`.

I also tried using Telnet to connect and received the same result. Could you please verify if the address `tcp://openapi-quote.longportapp.com:2020` is correct?
![CleanShot 2024-10-14 at 11 04 38](https://github.com/user-attachments/assets/3b9b7843-c643-4852-a923-fbef95d28ff9)

Thanks for your help!

**Comment by Patrick0308** [comment]
Where are you? openapi-trade.longportapp.com is a hong kong domain. If you are in mainland, please  try openapi-trade.longportapp.cn

**Comment by iiiyu** [comment]
> Where are you? openapi-trade.longportapp.com is a hong kong domain. If you are in mainland, please try openapi-trade.longportapp.cn

这个调用发生在新西兰。实际上.cn 我也试了，也是一样的结果。我现在就是奇怪的 trade 都能握手上， quote 都不能。 然后我试了试 go 的 sdk 是可以用的。 然后我看了里面用的是cn的域名。 难道说quote那边我需要做一点什么特别的事情么？我看了眼 go 的代码实在是一时半会不知道问题是哪里。 我的目的是想用 elixir 接一下接口。

**Comment by Patrick0308** [comment]
go sdk 默认使用香港的域名，除非设置 Region 为 cn。而且 go sdk 默认使用 websocket 协议连接 openapi-quote.longportapp.com  , 端口是 443。 你可以使用 ping 来确认一下网络延迟
```
ping openapi-quote.longportapp.com 
```

**Comment by iiiyu** [comment]
所以go sdk 是用的 websocket，并没有直接用 TCP 是吧。 那我找时间试试 websocket 。 ping 的延迟看上去还行。 毕竟我就是在本机
![CleanShot 2024-10-17 at 23 36 36](https://github.com/user-attachments/assets/05434bc1-e6f3-4229-8470-d33ca237bd50)

**Comment by Patrick0308** [comment]
@iiiyu 延迟还是挺高的。。

**Comment by sunfuze** [comment]
tcp 之前几乎没有使用，所以端口我们关掉了
